### ISSUE TITLE
Issue on Main Form buttons

### ISSUE THREAD

**Issue by rajeem** [ForNeVeR/OpenDBDiff#1]
When you resize the main form window, "new project" button is in front and the others are behind another panel
![opendbdiff issue](https://cloud.githubusercontent.com/assets/3981531/5641230/5a4c01e4-966f-11e4-97bc-2a47bc508048.PNG)

**Comment by ForNeVeR** [comment]
I am sorry, @rajeem, but this is not an official repository of OpenDBDiff. Please report bugs to the official repository: http://opendbiff.codeplex.com/
